# Based on: http://conda.pydata.org/docs/travis.html

sudo: false

# Travis-CI does not currently support Python and Mac OS X
language: c

os:
  - linux
  - osx

env:
#  - PYTHON_VERSION=3.5
  - PYTHON_VERSION=3.6

matrix:
  allow_failures:
  - os: osx
#  - env: PYTHON_VERSION=3.5

# before_script:
#  - "export DISPLAY=:99.0"
#  - if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then apt-get install xvfb; fi
#  - if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then "sh -e /etc/init.d/xvfb start"; fi
#  - sleep 3  # give xvfb some time to start

before_install:
  # Set the anaconda environment
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      curl https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -o miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi

  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a

  # create and activate a test-environment
  - conda create -q -n test-environment python=$PYTHON_VERSION
  - source activate test-environment

install:
  - conda config --set channel_priority true
  - conda config --prepend channels conda-forge
  - conda install -q numpy basemap pyside matplotlib netCDF4 gdal libgdal pyproj krb5 pyserial pillow
  - pip install gsw==3.0.6
  - if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then conda install xerces-c==3.2.0; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then conda install jpeg=8; fi
  - pip install --no-deps -e .

script:
  - python -m unittest discover

after_script:
  # If tests are successful, create a source distribution.
  # - python setup.py sdist
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then python setup.py bdist_wheel; fi
