version: 0.1.{build}-{branch}

branches:
  only:
  - master

environment:
  matrix:
    - PYTHON_VERSION: 2.7
      PYTHON_ARCH: x86
      MINICONDA: C:\Miniconda
    - PYTHON_VERSION: 2.7
      PYTHON_ARCH: x64
      MINICONDA: C:\Miniconda-x64
    - PYTHON_VERSION: 3.5
      PYTHON_ARCH: x64
      MINICONDA: C:\Miniconda3-x64

matrix:
  allow_failures:
    - PYTHON_VERSION: 3.5
      PYTHON_ARCH: x64
      MINICONDA: C:\Miniconda3-x64

install:
  - set PATH=%MINICONDA%;%MINICONDA%\Scripts;%PATH%

  # Install the build and runtime dependencies of the project.
  - "conda config --set always_yes yes --set changeps1 no"
  - "conda update -q conda"
  - "conda info -a"
  - "conda create -q -n test-environment python=%PYTHON_VERSION%"
  - "conda config --add channels hydroffice"
  - "conda config --add channels SciTools"
  - "conda config --add channels IOOS"
  - "activate test-environment"
  - "pip install wheel"

  # Check that we have the expected version of Python
  - "python --version"

  # Install dependencies
  - conda install -q numpy basemap pyside matplotlib netCDF4 gdal==1.11.2 libgdal==1.11.2 pyproj pyserial
  - pip install https://github.com/TEOS-10/python-gsw/archive/master.zip

build: off
build_script:
  - pip install --no-deps -e .

test: off
test_script:
  - python -m unittest discover

after_test:
  - "python setup.py bdist_wheel"

artifacts:
  - path: dist\*